return {
  "lewis6991/gitsigns.nvim",
  event = require "utils.lazyfile",
  opts = {},
  keys = {
    { "<leader>gj", "<cmd>Gitsigns nav_hunk next<cr>", desc = "Next Hunk" },
    { "<leader>gk", "<cmd>Gitsigns nav_hunk prev<cr>", desc = "Prev Hunk" },
    { "<leader>gs", "<cmd>Gitsigns (un)stage_hunk<cr>", desc = "Stage Hunk", mode = { "n", "v" } },
    { "<leader>gr", "<cmd>Gitsigns reset_hunk<cr>", desc = "Reset Hunk", mode = { "n", "v" } },
    { "<leader>gS", "<cmd>Gitsigns stage_buffer<cr>", desc = "Stage Buffer" },
    { "<leader>gp", "<cmd>Gitsigns preview_hunk<cr>", desc = "Preview Hunk" },
    { "<leader>gb", "<cmd>Gitsigns blame_line full=true<cr>", desc = "Blame Line" },
    { "<leader>tb", "<cmd>Gitsigns toggle_current_line_blame<cr>", desc = "Line Blame" },
    { "<leader>gh", "<cmd>Gitsigns git_branches<cr>", desc = "Branches" },
    { "<leader>gc", "<cmd>Telescope git_commits<cr>", desc = "Commits" },
    { "<leader>gC", "<cmd>Telescope git_bcommits<cr>", desc = "Branch Commits" },
    { "<leader>g?", "<cmd>Telescope git_status<cr>", desc = "Status" },
    { "<leader>gd", "<cmd>Gitsigns diffthis<cr>", desc = "diff" },
    { "<leader>gD", "<cmd>Gitsigns diffthis '~'<cr>", desc = "diff w/ Head" },
    { "<leader>tD", "<cmd>Gitsigns toggle_deleted<cr>", desc = "Deleted Hunks" },
  },
}
