return {}
-- return {
--     enables = false,
--     "stevearc/oil.nvim",
--     dependencies = { "nvim-tree/nvim-web-devicons" }, -- use if prefer nvim-web-devicons
--     ---@module 'oil'
--     ---@type oil.SetupOpts
--     opts = {
--         view_options = {
--             show_hidden = true,
--         },
--     },
--     keys = {
--         -- stylua: ignore
--         { "<C-n>", function() require("oil").open_float() end },
--     },
-- }
