local install = {
  "bash",
  "c",
  "cpp",
  "c_sharp",
  "cmake",
  "comment",
  "css",
  "dockerfile",
  "fish",
  "go",
  "graphql",
  "html",
  "http",
  "javascript",
  "jsdoc",
  "json",
  "json5",
  "jsonc",
  "lua",
  "make",
  "c",
  "markdown",
  "php",
  "pug",
  "python",
  "query",
  "regex",
  "rust",
  "scss",
  "tsx",
  "typescript",
  "vim",
  "vue",
  "yaml",
}
require("nvim-treesitter.configs").setup {
  -- ensure_installed = O.treesitter.ensure_installed, -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  ensure_installed = install,
  sync_install = true,
  -- ignore_install = O.treesitter.ignore_install,
  playground = { enabled = true, updatetime = 25 },
  highlight = {
    -- enable = O.treesitter.highlight.enabled -- true will disable the whole extension
    -- enable = {"c", "cpp", "c_sharp", "fish", "go", "php", "pug", "lua"},
    enable = true,
  },
  -- indent = {enable = true, disable = {"python", "html", "javascript"}},
  -- TODO seems to be broken
  indent = { enable = true },
  autotag = { enable = true },
}
