local ensure = {
  "bash",
  "c",
  "cpp",
  "c_sharp",
  "cmake",
  "comment",
  "css",
  "dockerfile",
  "fish",
  "go",
  "graphql",
  "html",
  "http",
  "javascript",
  "jsdoc",
  "json",
  "json5",
  "jsonc",
  "lua",
  "make",
  "c",
  "markdown",
  "php",
  "pug",
  "python",
  "query",
  "regex",
  "rust",
  "scss",
  "tsx",
  "typescript",
  "vim",
  "vue",
  "yaml",
}
require("nvim-treesitter.configs").setup {
  ensure_installed = ensure,
  sync_install = true,
  -- ignore_install = {},
  playground = { enabled = true, updatetime = 25 },
  highlight = {
    -- enable = {"c", "cpp", "c_sharp", "fish", "go", "php", "pug", "lua"},
    enable = true,
  },
  indent = { enable = true },
  autotag = { enable = true },
  context_commentstring = {
    enable = true,
  },
  rainbow = {
    enable = true,
    extended_mode = true,
    max_file_lines = nil,
    colors = {
      "#FF00FF",
      "#FFFF00",
      "#00FFFF",
      "#00FF00",
    },
  },
}
